# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 312
data_root: data/VOC2012

# arguments for training
epochs: 80
batch_size: 4 # per GPU x 2 GPUs
num_workers: 1
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
